---
page-layout: full
format: 
   html: default
   pdf: default
citations-hover: true
link-external-icon: false
link-external-newwindow: true
links-as-notes: true
tbl-colwidths: [5,20,50,25]
identifier-prefix: sch
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
---

Required textbook: @magill2020

+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| Week         | Date[^1]     | Study Content[^2]                                   | Assignments                              |
+==============+==============+=====================================================+==========================================+
| `WK01`       | Jan 22-28    | Intro to Course & Survival Skills                   | Read and study the Syllabus + Appendices |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK02`       | Jan 29-Feb 4 | Ch01 - The classification of motor skills           | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK03`       | Feb 5-11     | Ch11: Defining and assessing learning               | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK04`       | Feb 12-18    | Ch12: The stages of learning                        | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK05`       | Feb 19-25    | Ch14: Demonstration and verbal instructions         | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK06`       | Feb 26-Mar 3 | **Exam 1**                                          | LT-Update 1                              |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK07`       | Mar 4-10     | Ch15: Augmented feedback                            | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK08`       | Mar 11-17    | Ch16: Practice variability                          | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK09`       | Mar 18-24    | Spring Break                                        | --                                       |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK10`       | Mar 25-31    | Ch17: The amount & distribution of practice         | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK11`       | Apr 1-7      | Ch18: Whole and part-practice                       | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK12`       | Apr 8-14     | **Exam 2**                                          | LT-Update 2                              |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK13`       | Apr 15-21    | Ch09: Attention                                     | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK14`       | Apr 22-28    | Ch10: Memory Components, Forgetting, and Strategies | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK15`       | Apr 29-May 5 | Ch13: Transfer of learning                          | Quiz                                     |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| `WK16`       | May 6-12     | **Exam 3**                                          | LT-Update 3                              |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+
| Final's Week | May 11-17    | Finish and submit the reflection paper\             | Finish and submit assignments            |
|              |              | Record and submit the performance video\            |                                          |
|              |              | (Refer to Appendices A, B, C)                       |                                          |
+--------------+--------------+-----------------------------------------------------+------------------------------------------+

[^1]: Section 18905 meets online (via Zoom) on Tuesdays AND on campus (Jacaranda 3510) on Thursdays from 12:30-1:45 p.m.

[^2]: Exams are not cumulative.

::: callout-note
Section 18905 meets online (via Zoom) on Tuesdays AND on campus (Jacaranda 3510) on Thursdays from 12:30-1:45 p.m.
:::
