---
page-layout: full
format: 
   html: default
   pdf: default
citations-hover: true
link-external-icon: false
link-external-newwindow: true
links-as-notes: true
tbl-colwidths: [5,20,50,25]
identifier-prefix: sch
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
---

Required textbook: @magill2020

+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| Week         | Date[^1]     | Study Content[^2]                                   | Assignments                               |
+==============+==============+=====================================================+===========================================+
| `WK01`       | Jan 22-28    | Intro to Course & Survival Skills\                  | Read and study the Syllabus + Appendices\ |
|              |              | Ch01: The classification of motor skills            | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK02`       | Jan 29-Feb 4 | **Ch02: The Measurement of Motor Performance**      | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | **Ch03: Motor Abilities**                           | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | Ch09: Attention                                     |                                           |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | Ch10: Memory Components, Forgetting, and Strategies | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK03`       | Feb 5-11     | Ch11: Defining and assessing learning               | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | Midterm                                             |                                           |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK04`       | Feb 12-18    | Ch12: The stages of learning                        | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | Ch13: Transfer of learning                          |                                           |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
|              |              | Ch14: Demonstration and verbal instructions         |                                           |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK05`       | Feb 19-25    | Ch15: Augmented feedback                            | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK07`       | Mar 4-10     | Ch16: Practice variability                          | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK08`       | Mar 11-17    | Ch17: The amount & distribution of practice         | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK09`       | Mar 18-24    | Ch18: Whole and part-practice                       | --                                        |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK10`       | Mar 25-31    |                                                     | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK11`       | Apr 1-7      |                                                     | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK12`       | Apr 8-14     |                                                     | LT-Update 2                               |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK13`       | Apr 15-21    |                                                     | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK14`       | Apr 22-28    |                                                     | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK15`       | Apr 29-May 5 |                                                     | Quiz                                      |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| `WK16`       | May 6-12     |                                                     | LT-Update 3                               |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+
| Final's Week | May 11-17    | Final Exam                                          | Finish and submit assignments             |
|              |              |                                                     |                                           |
|              |              | Finish and submit the reflection paper\             |                                           |
|              |              | Record and submit the performance video\            |                                           |
|              |              | (Refer to Appendices A, B, C)                       |                                           |
+--------------+--------------+-----------------------------------------------------+-------------------------------------------+

[^1]: Section 18905 meets online (via Zoom) on Tuesdays AND on campus (Jacaranda 3510) on Thursdays from 12:30-1:45 p.m.

[^2]: Exams are not cumulative.

::: callout-note
Section 18905 meets online (via Zoom) on Tuesdays AND on campus (Jacaranda 3510) on Thursdays from 12:30-1:45 p.m.
:::
