---
title:  'Course Syllabus'
subtitle: |
            KIN 377 - Motor Learning\
            Department of Kinesiology\
            Cal State Northridge\
            Spring 2024 - Fully Online
latex-auto-mk: true
format:
  html:
    toc: true
    toc-location: right
    smooth-scroll: true
    number-sections: true
    link-external-icon: false
    link-external-newwindow: true
    anchor-sections: true
    links-as-notes: false
    citations-hover: true
    footnotes-hover: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    links-as-notes: false
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
table-striped: true
---

# Instructor Info {#sec-instructor-info}

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
| Dr. Furtado received a B.A. in Physical Education from the Federal University of Parana, Curitiba, PR - Brazil. He earned his M.S. and Ph.D. degrees in Motor Behavior from the University of Pittsburgh, PA. Dr. Furtado's line of research focuses on two main areas: (1) validation of observational models in psychomotor assessment instruments and (2) the relationship between motor skill competence, perceived motor competence, physical activity levels, and body composition. | **Office Hours\                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **See @sec-office-hours for more information         |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **Contact Info\                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **Email: ovandef\@csun.edu (see @sec-e-mail-policy)\ |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Office: Redwood Hall 289                             |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+

: {tbl-colwidths=\[50,50\]}

::: callout-note
Please note for our course communications: use the course mailing list for general questions about course content, assignments, or schedules. For private matters requiring confidentiality, email me directly at my CSUN email address (ovandef\@csun.edu). Avoid using the Canvas Inbox, as I do not monitor it and your message may be missed. These guidelines will ensure effective and timely communication throughout our course.

**Section 18943**: classsp24.18943-c\@csun.edu\
**Section 19272**: classsp24.19272-c\@csun.edu
:::

# General Information

## Course Description

Study of principles , theories, and research evidence regarding the nature of motor performance and learning with particular emphasis on factors that impact learning a skill through practice.

-   teaching
-   examples of principles
-   educational and clinical settings
-   include both catalog and my own description
-   do the same with the other items from the excel file

## Course Prerequisite

[KIN 200](https://catalog.csun.edu/academics/kin/courses/kin-200/): Foundations of Kinesiology (3)

## Course Format

This is Fully Online (FO) course offering in which all class sessions and exams are presented in an online environment. Fully online courses have no on campus meetings.

::: callout-caution
This course is not self-paced and is not the "softer, easier way"! This means that you have to **1) check in regularly and 2) respond to the weekly assignments.**
:::

::: callout-note
All activities, assignments and exams in this course will be completed via Canvas. To succeed in this course, you must have reliable access to a computer and internet connection. CSUN offers currently enrolled students the option to borrow devices such as computers and internet `hotspots` through its [Device Loaner Program](https://www.csun.edu/it/device-loaner-program).
:::

## Course Expectations and Goals

At the conclusion of this course, students should be able to:

1.  Describe the difference between motor learning and performance.
2.  Describe and understand different theories of control to explain how motor skills are performed and learned.
3.  Describe and understand the underlying mechanisms and processes involved in the production and control of movement.
4.  Discuss the relationship between attention and performance.
5.  Understand and demonstrate how factors relevant to the individual and to the environment influence the learning process.
6.  Understand and demonstrate how feedback types and schedules influence motor skill learning.
7.  Understand, describe, and demonstrate how practice schedules influence motor skill learning.
8.  Describe how and why the concept of individual differences is important in skill acquisition.
    1.  Describe and understand motor learning and control issues for special populations.
9.  Develop and implement methods of performance assessments.
10. Develop and implement a series of practice sessions designed to teach and/or learn a novel motor skill.

## Student Learning Outcomes (SLO'S)

1.  Apply an integrated kinesiological approach to encourage the adoption of healthy and physically active lifestyles, across diverse populations;
2.  Apply evidence-based practices to enhance the study of human movement;
3.  Demonstrate competent problem-solving strategies through intentional practices; and
4.  Demonstrate knowledge of kinesthetic forms, processes, and structures as they apply to the personal expression and culture of human movement.

## Textbook

{{< include inc_text-fasp.qmd >}}

## Additional resources

### Access to Computer & Internet

Although not required, it is suggested that you have access to a computer (not simply a tablet and/or smartphone) and Internet throughout this course. Note that CSUN students are eligible to [check out tech devices from CSUN at NO COST](https://www.csun.edu/it/device-loaner-program).

### Mini Juggling Balls

One of the requirements of this course is to learn a motor skill. If you select juggling, I suggest you to acquire the [mini juggling balls](http://goo.gl/X3EjLE), which are small and have the recommended weight for beginners.

::: callout-important
If you choose to use any object other than the mini juggling balls, understand that your performance may be **negatively affected** by it. When performing the exchange technique (required for this activity), at a given point, performers need to hold two objects in one hand. This becomes a problem if large objects are being used; i.e., tennis balls.
:::

### Speed Stacks Sport Stacking Set

If you choose to learn the cup stacking, I recommend you to acquire the [cups used in national and international tournaments](http://goo.gl/Y8HXt5), or grab a set of less expensive ones from Amazon or elsewhere.

You could also consider checking out one of the sets of professional cups available on Reserve (4th Floor) at the [CSUN Library](https://csu-un.primo.exlibrisgroup.com/permalink/01CALS_UNO/1r95rpr/alma991012367909202914).

::: callout-warning
Use cups specifically designed for cup stacking to get the best results and avoid negative impact on your performance and grades. ***Regular plastic cups are not suitable***.
:::

# Course Policy {#sec-course-policy}

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

# Course Communcation

In order to ensure efficient and effective communication throughout this course, I would like to establish clear guidelines regarding the preferred channels for course-related inquiries and personal matters.

1.  **Course Mailing List for General Questions**: For any queries or discussions relevant to the course material, assignments, schedules, or other general topics, I encourage you to use the designated course mailing list. This platform is not only conducive to fostering a collaborative learning environment, but it also allows for the sharing of information that may benefit the entire class. Please do not hesitate to post your questions there, as your peers might have similar inquiries or valuable insights.

2.  **Direct Email for Private Matters**: If you have any personal concerns, issues related to grading, or matters that require confidentiality, I kindly request that you contact me directly via my official CSUN email addressn (ovandef\@csun.edu). This will ensure that your concerns are addressed in a private and secure manner.

3.  **Non-Usage of Canvas Inbox**: Please be advised that I do not utilize the Canvas Inbox system for course communications. Consequently, messages sent through this channel may not receive a timely response or might be overlooked entirely. I strongly recommend adhering to the aforementioned communication methods to ensure that your needs are promptly and effectively met.

# Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

## Grading Policy {#sec-grading-policy}

-   **30%**(3): [Exams](#sec-exams) \[SLO's 2\]
-   **15%**(1): [Learning Task Performance](#sec-lt-performance) (final video submission) \[SLO's 1, 2, 4\]
-   **15%**(1): [Learning Task Reflection](#sec-learning-task-reflection) \[SLO's 1, 2, 4\]
-   **10%**(3): [Learning Task Updates](#sec-learning-task-updates) \[SLO's 1, 2, 4\]
-   **15% (na)**: Video Quizzes
-   **15% (na)**: Online Quizzes

::: callout-note
Two (2) Video Quizzes and one (1) Online Quiz with the lowest score will be dropped at the end of the term.
:::

## Grading Scale {#sec-grading-scale}

+---------------+-----------------+------------------+------------------+----------+
| A 93-100%\    | B+ 87-89.99%\   | C+ 77-79.99%\    | D+ 67-69.99%\    | F \<60%  |
| A- 90-92.99%  | B 83-86.99%\    | C 73-76.99%\     | D 63-66.99%\     |          |
|               | B- 80-82.99%    | C- 70-72.99%     | D- 60-62.99%     |          |
+---------------+-----------------+------------------+------------------+----------+

::: callout-important
Requests for an Incomplete (I) must conform to [university policies](https://bit.ly/3bDxwZi). Among other requirements, "I" is possible only for instances in which you are demonstrating passing work in the class.
:::

## Attendance Policy {#sec-attendance-policy}

Even though this course is online, it is important to "attend" regularly. This means logging into Canvas multiple times throughout the week.

## E-mail Policy {#sec-e-mail-policy}

CSUN uses email as the official communication method. Students must check their official CSUN email account regularly to stay up-to-date. Only emails sent to the official CSUN email account will be received.

::: callout-important
Use the course mailing list for general questions about course content, assignments, or schedules. For private matters requiring confidentiality, email me directly at my CSUN email address (ovandef\@csun.edu). Avoid using the Canvas Inbox, as I do not monitor it and your message may be missed. These guidelines will ensure effective and timely communication throughout our course. Ensure to save the email below to your contacts.

**Section 18943**: classsp24.18943-c\@csun.edu\
**Section 19272**: classsp24.19272-c\@csun.edu
:::

## Office Hours {#sec-office-hours}

{{< include inc-office-hours.qmd >}}

## Make-Up Exam Policy

Unless the student has discussed the situation with the instructor before the assignment's due date and an arrangement has been made, a missed assignment will result in a grade of zero. **Note that making "arrangements" will only be possible given the student provides a valid and written excuse from a reputable source**.

## Late Assignments

In case you haven't made any prior arrangements, submitting a late assignment will result in a 5% deduction per day for the first four days it is overdue. After the fourth day, all assignments will be considered closed.

<!--# Change this in Canvas every semester -->

## Extra Credit

The instructor will not be providing additional points for this particular course.

## Disabilities Policy {#sec-disabilities-policy}

Federal law mandates the provision of services at the university-level to qualified students with disabilities.

This instructor, in conjunction with California State University Northridge, is committed to upholding and maintaining all aspects of the federal Americans with Disabilities Act of 1990 (ADA) and Section 504 of the Rehabilitation Act of 1973. If you are a student with a disability and wish to request accommodations, please contact the office of Students with Disabilities Resources located in 110 Student Services Building, or call (818) 677-2684 for an appointment. Any information regarding your disability will remain confidential. Because many accommodations require early planning, requests for accommodations should be made as early as possible. Any requests for accommodations will be reviewed in a timely manner to determine their appropriateness to this setting.

## Academic Dishonesty Policy

*Please, **stop** and read the information below; this is important!*

Each student is expected to be familiar with, and abide by, the conditions of student conduct, as presented in the CSUN Catalog, with emphasis on sections entitled, Student Conduct Code, Academic Dishonesty, Faculty Policy on Academic Dishonesty, and Penalties. Any student engaging in academic dishonesty (e.g., cheating, fabrication, facilitating academic dishonesty, plagiarism) is subject to discipline, which may include a failing grade in the course, and may also be subject to more severe discipline by the University. Students are encouraged to visit the link below and become familiar with the Standards for Student Conduct.

<http://www.csun.edu/a&r/soc/studentconduct.html>

### Reflection Paper Submission

Plagiarism is a serious violation of the CSUN Student Conduct Code. Be aware that **borrowing** a paper from a student who completed this course previously and writing your paper based on that student's paper will be considered **PLAGIARISM**.

::: callout-important
Turnitin (see below) will detect such misconducts as it checks every submission against a database of papers, as well as against the Internet.
:::

::: callout-caution
Penalties: If caught, the student will receive a letter grade of "F" on BOTH the Reflection Paper and the Video Performance assignments, in which case the student will likely fail the course as these two assignments account for 40% of the course total grade.
:::

What is Turnitin?

You should be aware that the Reflection Paper will be submitted via Canvas, which is connected to [Turnitin](https://www.turnitin.com/). This is an automated system that instructors can use to quickly and easily compare each student's assignment with billions of websites, as well as an enormous database of student papers that grows with each submission. Accordingly, you will be expected to submit assignments through the Canvas Assignment Tool in electronic format. After the assignment is processed, as an instructor, I receive a report from *Turnitin* that states if and how another author's work was used in the assignment.

# Course Requirements

To succeed in this course, you will be required to complete several assignments. To avoid surprises, be proactive and review these assignments.

::: callout-note
I know how important it is for you to know your current grade in the class. That is why my priority is to grade most assignments (except for the paper) within 1 week of the deadline, which will be visible on the Canvas Gradebook.

If your grades are not posted within a week after the deadline, or you believe the grade is inaccurate, feel free to email me about the status of your grade.
:::

## Quizzes {#sec-quizzes}

Quizzes will be administered via Canvas and will assess the student's understanding of the topic covered each week. Students are allowed to utilize class notes and the course text to answer the questions; however, **collaboration with other students is not allowed**.

*Here are some other useful information about quizzes:*

1.  Quizzes are posted on Monday and remain open until Sunday at 11:59 pm. Once started, students have 20 minutes to complete and submit the each quiz.

2.  When taking quizzes, the questions will appear one at a time and locked after being answered. Thus, students are not allowed to go back and review answers after saving each question.

3.  Correct answers will only be shown to students after the deadline of each quiz.

4.  Refer to `Canvas` and the course sequence for due dates. Please, avoid waiting until the "last minute" to take the quiz. Taking the quizzes earlier will give you enough time to troubleshoot potential technical problems; therefore, plan accordingly.

5.  You will be given a **single** attempt on each quiz. This means you need to study the material before taking each quiz. All quizzes are timed. Students will be given 20 minutes to finish and submit a quiz.

6.  A quiz will only start if the student has a JavaScript-enabled web-browser. Contact [CSUN IT](https://www.csun.edu/it) should you run into technical issues when taking quizzes.

7.  Once opened, a quiz will appear in a full-screen pop-up window that covers all the other windows and has no navigation control

8.  It should be noted that the content of each quiz belongs to [McGraw Hill](https://www.mheducation.com/) (the publisher of our text). Therefore, federal copyright laws prohibit the dissemination of this material. It includes, but is not limited to, posting the quiz online and/or sharing the quiz with someone outside of the classroom.

## Exams {#sec-exams}

You be will be required to complete three exams while taking this course. Exams are taken online using the LockDown browser. Exams will be open on Monday morning along with a general study guide and be closed on Sunday at 11:59 p.m. Exams will be comprised of 30 multiple-choice type of questions.

## Learning Task Assignment {#sec-learning-task}

This assignment carries significant weight and contributes 40% towards your final grade in the course. It is crucial that you go through Appendix A (available at @sec-appendices) as soon as possible to acquaint yourself with the requirements of this task.

### Learning Task Performance {#sec-lt-performance}

*Refer to @sec-appendices for full requirements, but basically:*

-   You will be asked to choose either the 3-object Juggling or Cup Speed Stacking activity;
-   Then, you will be required to practice and learn the selected activity;
-   Before the end of the term (see @sec-course-sequence), you will be asked to video-record yourself performing the skill you have learned. This is the **Performance** portion of this assignment and accounts for 15% of the final grade.

### Learning Task Reflection

-   The second part of this assignment is a **Reflection Paper**, which also accounts for 20% of the final grade. As you practice and learn the selected skill, you will be advised to use the Motor Learning Principles (full details on Canvas) you will be exposed to while taking this course.
-   Throughout the term, you will be required to update me on your progress toward learning the selected skill (juggling or cup stacking). See Learning Task Updates below.

### Learning Task Updates

You will be submitting several updates throughout the term. These "updates" are meant to keep you on track and ensure you are taking advantages of all the learning techniques covered in this course to master the selected skill. More information about this assignment will be provided on Canvas.

## Video Quizzes {#sec-video-quizzes}

For each chapter, you will have access to one or more videos that are relevant to the assigned topic. These videos have embedded quizzes that cover the content of the video. **Even though Canvas allows you to take the video quizzes multiple times, ONLY THE FIRST ATTEMPT COUNTS.**

# Final (yet important) Notes {#sec-important-notes}

## How to Access our Course and Get Started

-   Log into Canvas: <https://canvas.csun.edu>
-   Under "My Courses," locate our course and click on it.
-   This will take you to the course home page.

## Technology Requirements and Support:

-   A computer and access to the internet (reliable connection)
-   Google Chrome (web browser)
-   A device to record video (phone, tablet, or laptop)

## What I Expect of You:

1.  Online classes are deceiving. Many times new online learners expect them to be easier than face-to-face classes and are surprised to learn how time intensive they are.
2.  Plan your schedule to ensure you have approximately 10 hours per week to spend on this class and take time to identify where and when you'll do your learning.
3.  Review the due dates for the assignments (see @sec-course-sequence) to orient yourself to the flow of the learning.
4.  This course requires regular engagement throughout each week. Plan to reserve a few hours each day to practice the skill you selected for the Learning Task assignment (see @sec-learning-task).

## Online Etiquette

All learners in this course will expect to abide by our community ground rules (see below).

Ground Rules: In an effort to ensure our learning community develops, thrives and sustains throughout our time together, the following ground rules will be in effect at all times.

1.  Consider yourself a member of a community. A community is a group of individuals who work together to support a common goal or interest. We are working together to support the successful achievement of our learning outcomes.
2.  Log-in and participate regularly to group conversations and activities.
3.  Treat the diverse contributions made by other community members with respect.
4.  Have patience and a sense of humor with technology.
5.  Be a learner. Keep an open mind when introduced to new ideas that may challenge your perceptions.
6.  Ask for help when you need it, and assist others when possible.
7.  Understand that communications shared through text have a higher likelihood of being misinterpreted than words that are spoken. Therefore, when you type a thought or a comment, read it carefully before you submit it. If you question the way it is worded, read it out loud to yourself. If you still question the way it's phrased, rewrite it.
8.  Contribute regularly to group dialogue, including discussion posts and replies. The contributions of each individual plays a role in the collective strength and diversity of our community.
9.  If, at any time, you feel that any of these ground rules has been violated by a member of our community, you are encouraged to bring your concern directly and immediately to Dr. Furtado. Clearly identify which ground rule has been violated and include specific evidence of the violation in your e-mail or phone call. Your concerns will be addressed promptly and in an individualized manner.

# Course Sequence {#sec-course-sequence}

{{< include sequence-fasp.qmd >}}

# Appendices {#sec-appendices}

# Appendices

It is important that you do not overlook the content of the appendices. Please make sure to read them thoroughly.

[HTML version](https://drfurtado.github.io/kin377/377-appendix-a_b_c.html) \| [PDF version](https://drfurtado.github.io/kin377/377-appendix-a_b_c.pdf)

# References {unnumbered}
