---
title: Skill Presentation
subtitle: KIN 377 Motor Learning | Cal State Northridge
format:
  html:
    toc: true
  pdf:
    toc: false
    toc-depth: 2
    number-sections: true
author:
  - name: Ovande Furtado Jr., PhD
    affiliations:
      - name: Cal State Northridge
    email: ovandef@csun.edu
bibliography: ./references.bib
csl: apa.csl
fontsize: 11pt
---

# Overview {#sec-overview}

In this assignment, you will choose a specific motor skill and create a detailed slide presentation. This presentation will cover the teaching process of a motor skill to a learner who is unfamiliar with the skill. Your presentation should utilize the frameworks and theories discussed in our course and align with the concepts detailed in @magill2017. This assignment will not only test your understanding of motor learning principles but also your ability to apply these principles in practical teaching scenarios.

# Steps {#sec-topic-selection}

1.  At the beginning of the term, you will be asked to submit 3 **motor skills** you can teach someone. You must be familiar with these motor skills.
    1.  Your instructor will choose one of the three skills you submitted and send you a confirmation.
    2.  Upon receiving confirmation, start working on this assignment - **Start by reading the content of** @sec-appendix-a.
2.  Work on the slide presentation throughout the term - `do not wait until the end of the term to work on this assignment.`
3.  Once done, record yourself presenting the slides.
    1.  Submit the slide presentation and the video recording by the deadline (refer to course's calendar).

# Recording the Presentation {#sec-recording-presentation}

-   Record you presenting the slides. Ensure the camera is `turned on` during the presentation and blur the background if possible.
    -   You may use platforms like Zoom, MS Teams, Google Meet (recommended) for recording your presentation.
    -   Find the instructions below:
        -   [Google Slides via Google Meet](https://www.perplexity.ai/search/How-do-you-O13EZkIoTM.2Q00ERDvdcg#0)
        -   [Google Slides via Zoom](https://www.perplexity.ai/search/How-do-you-O13EZkIoTM.2Q00ERDvdcg#1)
        -   [PowerPoint via Google Meet](https://www.perplexity.ai/search/How-do-you-O13EZkIoTM.2Q00ERDvdcg#2)
        -   [PowerPoint via Zoom](https://www.perplexity.ai/search/How-do-you-O13EZkIoTM.2Q00ERDvdcg#3)

# Submission {#sec-submission}

-   Ensure your slide presentation is clear, visually engaging, and well-organized.
    -   You may use MS PowerPoint, Google Slides (recommended), or the like to create your presentation. BUT, you must convert the file to PDF and ONLY submit this file along with your video file.
-   So, submit both the 1) **slide presentation** (in PDF) and 2) **video recording**.
    1.  Convert the presentation to PDF and save the file.
    2.  Record you slide presentation (see @sec-recording-presentation). Once done recording the presentation, locate the recorded video file.
    3.  Go to Canvas and locate the assignment `Skill Presentation` under `Assignments.`
    4.  Tutorials:
        1.  [Still images tutorial](https://arc.net/e/AD095DE4-35E2-4620-9A59-DA09A5B7FE6E)
        2.  [Video tutorial](https://mycsunemail-my.sharepoint.com/:v:/g/personal/ovande_furtado_csun_edu/EeSawGtvdEJOiC6Ytx2mVnUBgdRXds0gWlpkvIRYjHjD4Q?e=hpOlGM)

# Additional Guidelines {#sec-additional-guidelines}

-   Use professional language and include references to the textbook and any other academic resources to support your analysis.
-   Incorporate diagrams, images, or videos that enhance understanding of the motor skill, its breakdown, and teaching strategies.
-   Practice your presentation to ensure smooth delivery and adherence to the time constraints.

# Deadlines {#sec-deadlines}

Refer to the course's calendar on Canvas.

# Appendix A {#sec-appendix-a}

**The structure of the presentation**

1.  Introduction (1-2 slides)
    -   Introduce the motor skill you have chosen to teach.
    -   Assume this is a novel motor skill for the learner.

<!-- -->

2.  The Learner (1 slide)
    -   Describe the person who will be learning the selected skill, considering their specific context (e.g., a healthy middle-aged adult or an elderly post-stroke patient).

<!-- -->

3.  One-Dimension Skill Classification (1-2 slides)
    -   Categorize the chosen skill using the One-Dimension skill classification [@magill2017, p.10]:
        -   **Closed vs. Open Skill**: Define whether the skill is performed in a predictable environment (closed) or an environment that changes and requires adjustments during performance (open).
        -   **Discrete vs. Continuous vs. Serial Motor Skill**: Identify whether the skill has clearly defined beginning and end points (discrete), is repetitive with no obvious beginning or end (continuous), or involves a sequence of movements that are combined in a series (serial).
        -   **Gross vs. Fine Motor Skill**: Determine whether the skill requires large muscle groups (gross) or fine motor control (fine).

<!-- -->

4.  Skill Analysis (1-2 slides)
    -   Conduct a skill analysis for the selected skill as outlined by @magill2017 [p. 358].

<!-- -->

5.  Stages of Learning (2-3 slides)
    -   Refer to Fitts and Posner (1967) Three Stages of Learning, cited in @magill2017 [p. 274], and describe the expected changes in performance characteristics from the Cognitive to the Associative stage and from the Associative to the Autonomous stage, specifically tailored to the chosen skill.

<!-- -->

6.  Motor Learning Principles (3-4 slides)
    -   Select and define 3 Motor Learning Principles (see @sec-appendix-a) relevant to teaching your selected skill.
    -   Describe Application for Each Principle:
        -   Explain how you will use each principle in the teaching process.
        -   Provide specific strategies or methods for applying each principle.

<!-- -->

7.  Assessment of Skill Learning (1-2 slides)
    -   Describe the methods you will use to assess skill learning, referencing @magill2017 [p. 259].
    -   Include potential tests, observational strategies, and feedback mechanisms to measure the learner's progress and skill acquisition.

<!-- -->

8.  References (1 or more slides as needed)
    -   Cite sources throughout the slides, then create a reference list following the APA Style format.
    -   Refer to the section `References` below for an example.

# Appendix B {#sec-appendix-b}

## Evaluation Rubric

|                                                         |                                                                                                                            |                                                                                                           |                                                                                                                   |
|---------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| **Criteria**                                            | **Exemplary (17-20 points)**                                                                                               | **Satisfactory (10-16 points)**                                                                           | **Needs Improvement (0-9 points)**                                                                                |
| **Content Accuracy and Depth (20 points)**              | Comprehensive and accurate breakdown of the motor skill, with specific application of learning stages and principles.      | Accurate but less detailed application of learning principles and stages; some areas could be elaborated. | Contains inaccuracies or significant omissions; vague or incorrect application of learning stages and principles. |
| **Clarity and Organization (20 points)**                | Exceptionally well-organized and logical flow, making the presentation easy to follow.                                     | Adequately organized; logical flow with some rough transitions.                                           | Lacks coherent structure; difficult to follow with unclear transitions.                                           |
| **Engagement and Presentation Skills (20 points)**      | Engaging delivery with effective use of verbal and visual tools; presenter participate actively and confidently.           | Generally engaging; adequate participation, though some parts of the presentation could be more dynamic.  | Not engaging; monotone or lack of enthusiasm.                                                                     |
| **Use of Visuals and Supporting Materials (20 points)** | Visuals and materials are professionally designed, highly relevant, and enhance understanding significantly.               | Visuals support the presentation but could be improved in design or relevance.                            | Minimal use of visuals, or the visuals used are irrelevant or poorly designed.                                    |
| **Assessment of Skill Learning (20 points)**            | Assessment methods are innovative, well-explained, and tailored to the skill and learner; clear implementation strategies. | Assessment strategies are appropriate but lack detailed explanations or implementation details.           | Assessment strategies are poorly explained, inappropriate for the skill or learner, or missing.                   |

# Appendix C {#sec-appendix-c}

## **Applying Motor Learning Principles in Coaching Volleyball**

By @denny2010

**APA Style reference**

Denny, V. (2010). Applying motor learning principles in coaching volleyball. *Coaching Volleyball Magazine*, (June/July), 24--25.

Coaching volleyball is enhanced when coaches draw from a variety of disciplines to assist in teaching skill development. The discipline of motor learning focuses on motor skills and/or the improvement of motor skills and involves principles that can be implemented by coaches to aid in volleyball skill acquisition. Coaches using principles from motor learning literature will enable players to reach their full potential in learning and developing volleyball skills leading to a more effective performance on the court. The following is a two-part series, summarizing various principles from motor learning research and making applications for coaching the sport.

**Principle #1: Encoding specificity principle (The Practice Conditions Should Be Like the Game)**

It has been stated that if you want to learn how to play the game, then play the game. In motor learning, this is a memory principle called the "encoding specificity principle" which suggests that the more closely aligned the practice context is to the game context, the better the game performance. For volleyball coaches, this means striving to make the practice conditions as much like the game conditions as possible. For example, if you know you will be playing in a gym with a very low ceiling, practice passing balls at a lower level. If you are going to face a big middle hitter who cuts the angles in your next match, then have someone hitting those angles in practice. If you want your players to perform well during stressful games, set up similar pressure situations during practice. For example, playing loud music, making bad calls, or putting the server on the end-line to serve for game point after a long rally, are all examples of making practice more like the game. Practices would include everything and anything that could possibly be experienced during the game. As a coach, look for ways to guarantee players have already practiced everything before they actually see it in the real game, and always be analyzing practices by evaluating how well you are training your players for actual game performance.

**My own comments:**

*The practice conditions should approximate as much as possible the test conditions. In practicing the chosen skill, consider this principle. Because you will be required to video record yourself, it is important you video record yourself a couple of times while practicing. Performers tend to get nervous when they find out they have to perform in front of other people and/or in front of the camera.*

*In addition, it is essential you are consistent when it comes to equipment and location. You must choose the equipment that will be used during practice asap.*

*If juggling is your choice, then you must decide whether to use bean bags, balls, or any other object. I strongly advise you to choose the small bean bags you can find in local toy stores or Amazon (<https://goo.gl/yvaWU5>).*

*If speed cup stacking is your choice, you must decide which kind of cups you will use for practice. Last time I checked, this set of cups (<https://goo.gl/QrJZU9>) was less than \$5 on Amazon. Do NOT choose regular plastic cups as they will negatively affect your performance.*

**Principle #2: Practice variability principle - The Practice Conditions Should Provide for Variability (blocked vs random)**

A second motor learning principle that is closely related to the encoding principle is called the "contextual interference principle" which stresses that random types of practice conditions are usually best. For example, if you are working on passing, it is best not to just practice passing from the same spot over and over again. This is called block practice and is not at all like the game of volleyball. How often does the player stand in one spot passing ten balls in a row from the same server from the same area? In random practice, the player might be asked to serve-receive 10 different types of serves from 10 different places from several different types of servers on the court. This random practice schedule best prepares passers to receive in the game. A further application would be after serve-receive, have players practice coming in for different types of sets and hits along the net with a full team coverage formation. Random practice has been proven to be effective in most situations. The only time random practice is discouraged is with beginners. For beginning players, coaches should start with a block schedule, practicing the same skill in the same way under the same condition repeatedly. The problem with most coaches, however, is that they continue this blocked practice schedule long after the athlete has acquired the basic skill pattern. Once the basic skill is demonstrated, random practice should be introduced.

**My own comments:**

*Random practice variability is more useful when learning "open skills". Both juggling and speed cup stacking* are*considered "closed skills", and, therefore, requires blocked practice. With open skills, the environmental features determine when to begin the action. In basketball, for instance, when dribbling the ball toward the basket while opponents are trying to steal the ball. This is an example of "open skill" since the features of the environment are not predictable. On the other hand, the free-throw shooting in basketball is considered a "closed skill". The features of the environment are predictable and the player decides when to initiate the action.*

**Principle #3: Learning Occurs in Three Distinct Stages**

Motor learning is complex and consists of three distinct stages. The cognitive stage is when the learner creates a mental picture of the skill to be executed along with processing the visual, kinesthetic, and auditory cues needed for the skill. Performance during this initial stage is full of questions and errors as the learner attempts to get an idea of how to do the skill. During the second stage, called the associative stage, the learner begins to understand how to do the skill and "associates" the movement with environmental cues. This stage is sometimes called the refining stage since learners begin to narrow the motor response and identify and correct errors on their own. The final stage of motor learning is termed the autonomous stage since the performance of the skill is now automatic. At this stage the learned skill is now a habit, requiring little attention. In order to reach this highest level, many years of practice are needed, and not all performers will achieve this final stage. For coaches, it is important to identify which stage a player is present since different stages require different coaching skills. During the initial cognitive stage, appropriate and timely feedback is needed to help the novice performer understand how to do the skill and how to correct errors. The coach is providing lots of encouragement along with appropriate feedback during the cognitive stage. During the associative stage, the coach's role shifts towards refining techniques. During this stage, the coach waits and allows the player to identify his or her own performance errors and correction. While the emphasis is on refinement, there are ample opportunities for practice to develop the consistency of the skill performance. Working with athletes in the final autonomous stage, the role of the coach again is different. Now the emphasis is on developing strategies and tactics for using the skill in a variety of game situations.

**My own comments:**

*Note that I do not consider the stages of learning as a motor learning principle per se. I treat the stages of learning as a separate section of the Reflection Paper (please refer to this assignment for more information).*

**Principle #4: Transfer of learning principle (Consider Transfer of Learning When Teaching New Motor Skills)**

Transfer of learning is the effect previous experiences have on the learning of a new skill or performing a skill in a new context. The concept of transfer lays the foundation for all of skill learning. Transfer of learning can be positive, negative, or neutral. Volleyball coaches should be aware of the transfer of learning effect and utilize it to help with teaching new skills to players or teaching already learned skills in new contexts. Positive transfer provides the foundation for teaching skill progression. Once a skill is learned, it can be transferred to new settings, or be the foundation for new skill learning. An example of transfer would be the overhand throwing pattern. Early in a child's development, the correct overhand pattern should be established. This skill can then be applied across different settings and into new sport skills. In volleyball the spike and jump serve both derive from the basic overhand pattern. Ensure that this fundamental skill is acquired at an early age so that positive transfer can occur later in volleyball skill learning. While positive transfer is a powerful tool, coaches should be aware of the role that negative transfer can play as well. Although negative transfer is temporary, it does initially hinder or hurt learning a new skill. In volleyball, an example of this could be when players initially learn to jump off two feet when spiking, and then the coach tries to teach the basic one-foot take-off for the slide. Since negative transfer is not permanent, the coach should be patient as players work on learning similar, but different skills.

**My own comments:**

*When practicing your chosen skill reflect upon previous experience acquired when practicing a similar skill. When doing so, consider whether there was a positive or negative transfer of learning when learning juggling or speed cup stacking. If so, you may discuss how such an experience affected the learning process of your chosen skill. Make sure to provide details.*

**Principle #5: Action-effect principle (Focus Attention on the Movement Effects Rather Than Just the Movement)**

Traditionally, coaches have the athlete focus on the internal movement of skills. For example, feedback statements such as "keep your elbows locked"or "reach and snap" have been the standard performance cues used for teaching the basic skills of volleyball. While such statements focus on the movement action rather than the effects of the movement, motor learning research suggests **that focusing on the external effects of movement also has a positive effect on skill acquisition**. As volleyball coaches, we should explore the effectiveness of using a more external focus of attention when instructing our athletes. For example, when teaching the basic overhand serve, instead of cues such as "keep your elbow high; step forward with the opposite foot, and reach and make contact," shift the focus to the external effects and see the results. External focus cues might include "see the ball up, step towards the target", or "hand to the ball to the serving zone." When providing feedback for the basic pass, teaching cues such as "keep the ball low" or "see the pass to the target" might be added with "thumbs together and lock elbows" or "lift with the legs." An external focus enables the performer not to concentrate so much on the movement itself, but rather on the effect or outcome of the movement and is effective. Coaches always desire to enhance the performance of their athletes. Information from various disciplines such as motor learning can help assist the coach with this process.

**My own comments:**

*When practicing your chosen skill you could apply this PML by shifting from internal to external focus and assess whether the principle was effective. As pointed by Denny (2010), by focusing on external features of the performance learners will pay less attention to the movement itself. This is especially helpful when the learners are moving from the cognitive to the associative state of learning. When reading the content of chapter 12 (Magill & Anderson, 2017), you will realize that learners entering the Fitts and Posner second stage of learning (associative) will focus less and less on the specific movements needed to perform a given skill.*

**#Principle #6: Augmented feedback principle (Feedback is Essential for Skill Learning)**

Perhaps there is no more conclusive evidence in motor learning literature than the effectiveness of feedback to enhance skill acquisition. In addition to task intrinsic feedback, which is provided through the senses of the learner, augmented feedback provides additional information helping the learner acquire the desired skill performance. A coach providing appropriate augmented feedback to the player regarding the performance of a skill is very helpful. Augmented feedback may come in different forms such as a coach providing verbal feedback. For example, when the coach remarks, "You served 8 of 10 balls in-bounds in zone three," this type of augmented feedback is called knowledge of results. While KR is often redundant with task intrinsic feedback, it may be needed when task intrinsic is not available or is unclear. Another type of verbal feedback is knowledge of performance. KP is when information is given regarding the specific characteristics of the performance. For example, a coach using KP informs the hitter that she dropped her elbow prior to the spike. This type of verbal information is descriptive knowledge of performance, as the feedback "describes" the act, and is recommended for more advanced players. For beginners, prescriptive KP is more effective such as telling a beginner to keep their elbow high when spiking. Besides verbal feedback, other examples of using augmented feedback include videotape recordings and movement kinematics such as the Dartfish software program.

**My own comments:**

*When practicing your chosen skill you should definitely incorporate this MLP into your practice. There are several ways to receive feedback while practicing and a length discussion is provided in our text. Even if you decide not to add this MLP in your reflection piece, considering it during practice will help you tremendously.*

**Principle #7: Augmented feedback principle (More Is Not Always Better)**

While feedback is extremely beneficial in skill acquisition, more is not necessarily better. In fact, asking learners to rate their own performance before providing augmented feedback may actually enhance the feedback effectiveness and help players not become so dependent on the coach providing all the feedback. There are numerous ways to decrease the amount of feedback provided, helping players become independent learners. For example, having players perform several attempts of a skill before providing augmented feedback (called summary feedback) can allow them to engage in a cognitive/kinesthetic skill analysis before hearing from the coach. A method called self-selected feedback suggests players only receive feedback from the coach when the players request feedback. Another approach of providing less rather than more feedback is termed "bandwidth feedback" which entails establishing an acceptable range or criterion of performance error, and only providing feedback once the player is outside that range. These approaches for reducing feedback delivery are helpful for coaches and players since it is a systematic reduction of feedback based on individual skill levels. So while feedback is essential for skill learning, more is not always better.

**My own comments:**

*The principle #7, which was discussed by Denny (2010), is simply an extension of principle #6. As you will see, Magill and Anderson (2017) will address principle #6 and #7 as one single principle and call it Augmented Feedback (Chapter 15).*

**Principle #8: Whole vs Part practice principle (Consider Organization and Complexity When Practicing the Whole Skill or Part of the Skill)**

Perhaps no other motor learning topic is debated as much as the whole/part practice question. When practicing a volleyball skill, which type is more effective? To practice the entire skill or to practice parts of the skill? One way for volleyball coaches to solve this dilemma is to conduct a skill analysis for each of the six volleyball skills (serving, passing, setting, hitting, blocking, and digging) and determine the complexity and the organization of each skill. The complexity of the skill consists of the number of parts or components while the organization of the skill involves the relationship among the various parts. If a skill is highly organized, it means that one part is dependent on the previous components. After doing the skill's task analysis, the general principle is if the skill is high in complexity and low in organization then the part method is better. For example, serving in volleyball would involve several components or parts to the skill, but these parts are not interdependent to one another; so the part method would be more appropriate. However, when a skill is low in complexity and high in organization practicing the whole skill is more appropriate. For example, spiking in volleyball involves parts that are highly dependent on one another. The approach, jump, and arm swing all work interdependently in order for the entire skill to be successful, thus the whole method is more appropriate, and this is especially true when working with beginners. The whole/part debate will continue among volleyball coaches, but determining the complexity and organization of the various skills may provide some guidance regarding which practice approach is better to use during practice skill instruction.

**My own comments:**

*This is a very important principle that will help you when practicing your chosen skill. You will realize that practicing juggling as a whole will produce the best results. This is because juggling is considered high and complexity and high organization (refer to Magill & Anderson, 2017 for details). Now, some will find it helpful to practice a simplified version of the skill (a type of part practice called simplification). Practicing with scarves, for instance, is an example. Notice that you are not trying to apply the part practice to the actual characteristics of the skill of juggling (see the listed 7 characteristics in the picture below).*

*Now, with the skill of speed cup stacking, one would benefit by employing the part practice method. In this case, the complexity is high but the organization is low. We break up the skill into parts and practice each part separately before practicing it as a whole. For instance, when practicing the 3-6-3 sequence, it is recommended that you practice the 3 up/down part separate from the 6 up/down part.*

**Principle #9: Distribution of practice principle (Practices Should Be Short and Frequent)**

This principle relates to **mass** versus **distributed** practice schedules. A mass practice schedule will have fewer practice sessions than a distributed schedule and will be fewer in number, while a distributed practice schedule will have the same amount of time allotment, but across more sessions making the sessions shorter in length. For the majority of volleyball coaches, decisions regarding the amount of practice time may or may not be within their control, but how long each practice is, and how often the team should practice are legitimate concerns that need to be addressed. The motor learning research suggests that practices can be too long and not as productive as shorter practices, so when in doubt, go for a shorter practice session, rather than a longer one. If more practice is needed, add additional practice sessions instead of lengthening the specific practice schedule.

**My own comments:**

*Consider using this PML when practicing your chosen skill. Your practice sessions should be short with some time for resting in between sessions.*

**Principle #10: If You Want To Get Better at Playing Volleyball, Play the Game of Volleyball**

The final motor learning principle for coaches to remember repeats the first tenant presented at the beginning of this series. Since repetition aids learning, this critical principle needs repeating; practice like the game. The best practices increase skill learning that can be transferred to the real game setting. During practice, if coaches increase time on game-related skills and increase opportunities to learn the skills in the context of the game, players will get better at playing the game of volleyball. Remember when volleyball coaches had players passing, setting, or spiking against the wall during practices. The question no one asked was "how often during the volleyball game will"passing", "setting", or "spiking" against the wall be necessary"? Many of our practice drills do not simulate the game conditions. It has been stated that the best passing drill is a pass/set/hit drill; the best setting drill is a pass/set/hit drill, and the best hitting drill is a pass/set/hit drill. In other words, if you want to get better at playing the game, then play the game. For volleyball coaches, this means designing drills to simulate the same skills needed in the game. If it isn't game-like, don't do it. Always be analyzing practices, changing drills, and incorporating mini-games, wash drills, and controlled scrimmages, so that practice looks like the game of volleyball. If you want your players to get better at playing volleyball, then let them play volleyball.

Effective volleyball coaches work hard to enhance the performance of their players. Information from various disciplines such as motor learning can help assist them with this process. This article looked at 10 principles from motor learning literature along with applications for teaching/coaching volleyball skills. Although certainly not exhaustive of all motor learning concepts, these principles do provide a solid pedagogical foundation for coaches developing successful players and effective teams.

**My own comments:**

*Refer to principle #1*

# References {#sec-references .unnumbered}
