---
title: Attention
subtitle: "KIN 377 Motor Learning - Spring 2024 @ CSUN"
format: 
  pdf:
   toc: false
  docx: default 
author:
  - name: Ovande Furtado Jr
    orcid: 0000-0003-3847-6314
    email: ovandef@csun.edu
    affiliations: Call State Northridge
date: last-modified
footer:  "[https://drfurtado.github.io/kin377/](https://drfurtado.github.io/kin377/)"
logo: "/images/logo.png"
bibliography: references.bib
csl: apa.csl
license: CC BY-NC-ND
---

## Credits

This presentation was based on Chapter 09 - Attention from @magill2020.

## Learning Objectives

​- Define the term \_\_\_\_\_\_\_ as it relates to the performance of motor skills ​- Discuss the concept of \_\_\_\_\_\_\_ \_\_\_\_\_\_\_ and identify the similarities and differences between \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ central-resource theories of attention capacity. ​- Describe \_\_\_\_\_\_\_'s model of attention as it relates to a motor skill performance situation ​- Describe the differences between \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ theories of attention capacity ​- Discuss \_\_\_\_\_\_\_ techniques that researchers use to assess the attention demands of performing a motor skill. ​- Explain the types of \_\_\_\_\_\_\_ \_\_\_\_\_\_\_ a person can employ when performing a motor skill. ​- Define \_\_\_\_\_\_\_ \_\_\_\_\_\_\_ \_\_\_\_\_\_\_ and describe how it relates to attention capacity limits and motor skill performance. ​- Discuss how skilled performers use \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ motor skills in visual search.

## ​​Think, pair, and share activity

-   Think about a motor skill that you perform that requires you to do more than one thing at the same time \~ \_\_\_\_\_\_\_ seconds ​- Now, describe this motor skill to your partner. As you do so, talk about how you can simultaneously perform these multiple activities by identifying what you think about, what you do not think about, and what you visually focus on as you perform these activities - \~ \_\_\_\_\_\_\_

## The concentration test

::: {.content-visible when-format="html"}
{{< video https://youtu.be/q2PaH-NRBKY >}}
:::

## Defining Attention

​- Attention refers to several characteristics associated with \_\_\_\_\_\_\_, \_\_\_\_\_\_\_, and \_\_\_\_\_\_\_ activities that establish limits to our performance of motor skills. ​- According to scientists, attention limits influence performance when we do more than \_\_\_\_\_\_\_ simultaneously.

## Agenda

1.  Attention and Multiple-task Performance
2.  Attention Theories
3.  Dual-task procedures for assessing attention demands
4.  Focusing attention
5.  Attention and Automaticity
6.  Visual search and motor skill performance
7.  Training visual search strategies
8.  Points for the practitioner

## 1. Attention and simultaneous performance of multiple activities

## Attention and Multitasking

When we simultaneously perform multiple tasks (for example, driving a car, listening to a CD, and talking with a passenger), we sometimes:

​- Experience no difficulties in performing all the tasks, but ​- Cannot do all the tasks as \_\_\_\_\_\_\_ as we would like

​**WHY?**

​The answer relates to attention as a \_\_\_\_\_\_\_-limiting factor.

## 2. Attention Theories

​### Filter theories (known as bottleneck theories). - Difficulty doing multiple tasks at one time because of the inability to \_\_\_\_\_\_\_ process multiple stimuli. - The human brain is like a computer: \_\_\_\_\_\_\_ \> \_\_\_\_\_\_\_ \> \_\_\_\_\_\_\_ - Bottleneck: Along the way, the system \_\_\_\_\_\_\_ out info NOT selected for further processing

​Popular for many years, but… - Research \> Information-processing functions could be carried out \_\_\_\_\_\_\_ - How to explain attention limits? - Is the result of the limited availability of \_\_\_\_\_\_\_ (similar to financial resources)?

### Theories emphasizing attentional resource limits

-   We can perform \_\_\_\_\_\_\_ simultaneously, as long as the resource capacity limits are not exceeded.
-   What if these limits are exceeded?
-   We experience difficulty performing one or more of these tasks (remember the tap/rub activity?)

The question about the number of sources - View 1 \> there is \_\_\_\_\_\_\_ from which all attentional resources are allocated - View 2 \> there are \_\_\_\_\_\_\_ sources for resources

## Central-resource capacity theories of attention.

-   Attention-capacity theories propose one \_\_\_\_\_\_\_ of attentional resources for which all activities requiring attention compete.
-   Financial analogy \> one source from which all activities must be \_\_\_\_\_\_\_

## Kahneman's Attention Theory

​- Kahneman's attention theory: An example of a \_\_\_\_\_\_\_ resource theory. - A single source of mental resources from which we derive cognitive effort is presented as a "\_\_\_\_\_\_\_" of resources that has a \_\_\_\_\_\_\_ capacity. - Available attention can vary depending on certain conditions: - The \_\_\_\_\_\_\_, the \_\_\_\_\_\_\_, and \_\_\_\_\_\_\_ characteristics

## Three rules that people use to allocate attention resources when performing multiple tasks.

1.  \_\_\_\_\_\_\_ to ensure completion of at least one task
2.  Enduring dispositions: Involuntary attention to at least two types of characteristics of events.
    -   Event is \_\_\_\_\_\_\_ for the situation in which it occurs.
    -   \_\_\_\_\_\_\_ of the event to us personally.
3.  Momentary intentions.
    -   People allocate attention according to their specific \_\_\_\_\_\_\_.
    -   Can be \_\_\_\_\_\_\_ or directed by an \_\_\_\_\_\_\_

## Multiple Resource Theories

​- Alternative to \_\_\_\_\_\_\_ theories. - Propose that we have \_\_\_\_\_\_\_ for attention. - Each source has a \_\_\_\_\_\_\_ capacity

Wickens \> Resources for processing info are available from 3 sources: 1. \_\_\_\_\_\_\_ (vision, limbs, and speech) 2. \_\_\_\_\_\_\_ (perception, memory encoding, response output)\
3. \_\_\_\_\_\_\_ (verbal codes, spatial codes)

​Success in performing two or more tasks simultaneously depends on whether those tasks demand our attention from a \_\_\_\_\_\_\_ or from \_\_\_\_\_\_\_ resources.

## 3. Dual-task procedures for assessing attention demands

​Dual-task procedure determines \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ of the simultaneous performance of two different tasks. - Primary task is the \_\_\_\_\_\_\_. - Secondary task performance is the basis to make inferences about the \_\_\_\_\_\_\_ of the primary task.

## 4. Focusing Attention

Attentional focus is the directing of attention to specific aspects of our \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_ environment.

### Width of focus

-   Focus on environmental and mental activities can be \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_

### Direction of focus

-   Focus can be \_\_\_\_\_\_\_ (cues in the environment) or \_\_\_\_\_\_\_ (internal thoughts, plans, problem-solving activities)

### Attention switching

-   The changing of \_\_\_\_\_\_\_ \_\_\_\_\_\_\_.

{{< video images/soccer-pass.mp4 >}}

## To pass a soccer ball, one needs to...

## Focusing Attention on Movements versus Movement Effects

Does \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_ direction of attentional focus matter?

### Action effect hypothesis (Prinz, 1997) explains:

-   Proposed benefit of \_\_\_\_\_\_\_ focus during performance
-   Focus attention on \_\_\_\_\_\_\_ (i.e., "effects") of movements rather than on the \_\_\_\_\_\_\_ themselves

Why: constrained action hypothesis - Performer consciously attempts to \_\_\_\_\_\_\_ performance - Reverses to earlier, less \_\_\_\_\_\_\_ form of movement control

## 5. Attention and Automaticity

Is attention linked to \_\_\_\_\_\_\_?

Automaticity = Performance of a skill (or its parts) with \_\_\_\_\_\_\_ on attention capacity. - Relates to evaluation of the \_\_\_\_\_\_\_ in the component of Kahneman's model of attention. - Some problems require \_\_\_\_\_\_\_, and effortful mental activities are influenced by \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_. - \_\_\_\_\_\_\_ brain areas are active when tasks are automatized - Example: \_\_\_\_\_\_\_ (2005) fMRI based research.

## Examples

{{< video images/dribble-exp.mp4 >}}

{{< video images/dribble-novice.mp4 >}}

## 6. Visual Selective Attention (VSA)

### Definition of VSA

-   The term refers to \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ performance-related information in the performance environment.

### Visual search

-   \_\_\_\_\_\_\_ relevant information in the environment, enabling a person to determine how to \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ a skill in a specific situation.

### Eye movements and visual selective attention

-   Device can track the \_\_\_\_\_\_\_ while people observe a scene.
-   What a person is visually attending to is inferred from the "\_\_\_\_\_\_\_" (locus of central vision).

What is the relationship between eye movements and visual attention? - Does what a person \_\_\_\_\_\_\_ (point of gaze) indicate where \_\_\_\_\_\_\_ \_\_\_\_\_\_\_ is directed?

## Selective Attention and Point of Gaze

-   Directing visual attention to an environmental feature without \_\_\_\_\_\_\_ at it is possible.
-   Remember, eye-movement recordings track \_\_\_\_\_\_\_ and not \_\_\_\_\_\_\_ vision.

Rethink the moto: 'Keep your eyes on the \_\_\_\_\_\_\_ at all times.'

## How We Select Visual Cues

​### Visual search and intended actions - The performer looks for specific cues in the performance environment, enabling them to achieve a specific \_\_\_\_\_\_\_. - Example: \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ (2002) demonstrated that the focus of initial eye movements differed when participants were told to point to or grasp an object.

### Feature integration theory

-   Initial visual search is based on specific features, such as \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_.
-   Selection of features of interest occurs when a person focuses the \_\_\_\_\_\_\_ on the master map of all features.

## Visual Search and Motor Skill Performance

​Visual search helps gather info that influences three aspects of the action control process: 1. Action \_\_\_\_\_\_\_ 2. \_\_\_\_\_\_\_ of the selected action\
3. \_\_\_\_\_\_\_ of action initiation

Note that these three preparation processes are influenced by visual search in \_\_\_\_\_\_\_ motor skills and \_\_\_\_\_\_\_ motor skills.

Relearning how to pick up a coffee mug (closed skill) - Ask a patient to assess the content of the mug before movement initiation: - Full, hot, etc. - Shape of the handle

Passing a soccer ball after receiving it from goalkeeper (open skill) - Ball speed - Pressure

## Tennis serve example

## 7. Training Visual Search Strategies

### Do we need to train it?

-   Visual search success is based on \_\_\_\_\_\_\_ in specific performance situations.
-   These strategies are often acquired without \_\_\_\_\_\_\_ training and without the person's \_\_\_\_\_\_\_ awareness of the strategies they use.

Some specific cases it may help. See the Quiet Eye in the next slide.

## The Quiet Eye

​- Refers to the amount of time devoted to the \_\_\_\_\_\_\_ just before movement initiation. - It is directed to a \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_ in the performance context. - It is a \_\_\_\_\_\_\_ of the performer's gaze. - Its onset occurs just before the \_\_\_\_\_\_\_ common to all performers of the skill. - Its duration is \_\_\_\_\_\_\_ for elite performers.

{{< video https://youtu.be/vhf8DMYNgi8 >}}

## Points to the Practitioners

1.  The capability to do multiple activities simultaneously when performing a motor skill can be \_\_\_\_\_\_\_-\_\_\_\_\_\_\_. This means that a person may succeed more in some situations than others. Note these differences and use them to design further instruction and practice.

2.  People will be more likely to be \_\_\_\_\_\_\_ while preparing to perform, or performing, a motor skill when events occur in the performance environment that is not usually present in this environment.

3.  Skilled individuals will be more likely to perform at their best when their \_\_\_\_\_\_\_ or \_\_\_\_\_\_\_ levels are optimal for performing the skill in the situation they will experience.

4.  People will perform motor skills better when they focus their \_\_\_\_\_\_\_ (i.e., what they "think about") on the \_\_\_\_\_\_\_ of the movement rather than on their own movements.

5.  You can enhance a person's visual selective attention in performance situations by providing many opportunities to perform a skill in various situations in which the most \_\_\_\_\_\_\_ remain the same in each situation.

6.  Train people to focus on the most relevant cue in the performance environment and then maintain \_\_\_\_\_\_\_ with that cue just before initiating movement – this relates to 'quiet eye'.

## References
